# CoreDNS with ad-blocking for enterprise DNS management
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns-adblock
  namespace: dns-system
  labels:
    app.kubernetes.io/name: coredns-adblock
    app.kubernetes.io/component: dns-server
    app.kubernetes.io/part-of: nerv-platform
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: coredns
      version: "1.32.0"
      sourceRef:
        kind: HelmRepository
        name: coredns
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    # Custom CoreDNS configuration with ad-blocking
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          # Blocklist plugin for ad-blocking (industry standard approach)
          - name: blocklist
            parameters: |
              /etc/coredns/blocklists/ads.txt
              /etc/coredns/blocklists/malware.txt
              /etc/coredns/blocklists/tracking.txt
          
          # Local zone for cluster services
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          
          # Prometheus metrics
          - name: prometheus
            parameters: 0.0.0.0:9153
          
          # Health check
          - name: health
            parameters: 0.0.0.0:8080
          
          # Ready check
          - name: ready
          
          # Cache for performance
          - name: cache
            parameters: 30
          
          # Loop detection
          - name: loop
          
          # Reload configuration
          - name: reload
          
          # Load balancing
          - name: loadbalance
          
          # Forward to upstream DNS (Cloudflare/Quad9 for security)
          - name: forward
            parameters: . 1.1.1.1 9.9.9.9
            configBlock: |
              prefer_udp
              health_check 5s

    # Deploy as LoadBalancer service for network-wide DNS
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: nerv-pool
      ports:
        dns:
          port: 53
          protocol: UDP
          targetPort: 53
        dns-tcp:
          port: 53
          protocol: TCP
          targetPort: 53

    # Resource configuration for production
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # High availability
    replicaCount: 2
    
    # Anti-affinity for reliability
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: coredns-adblock
              topologyKey: kubernetes.io/hostname

    # Standard security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
      capabilities:
        add:
          - NET_BIND_SERVICE
        drop:
          - ALL
      readOnlyRootFilesystem: true

    # Node scheduling
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    # Monitoring integration
    serviceMonitor:
      enabled: true
      namespace: dns-system
      path: /metrics
      port: 9153

---
# ConfigMap with blocklists (industry-standard sources)
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-blocklists
  namespace: dns-system
  labels:
    app.kubernetes.io/name: coredns-blocklists
    app.kubernetes.io/component: dns-configuration
    app.kubernetes.io/part-of: nerv-platform
data:
  # Ad-blocking lists (enterprise-friendly sources)
  ads.txt: |
    # Steven Black's unified hosts (industry standard)
    # Updated daily, minimal false positives
    # Source: https://github.com/StevenBlack/hosts
    0.0.0.0 doubleclick.net
    0.0.0.0 googleadservices.com
    0.0.0.0 googlesyndication.com
    0.0.0.0 googletagmanager.com
    0.0.0.0 facebook.com
    0.0.0.0 analytics.google.com
  
  malware.txt: |
    # Malware Domain List (security focus)
    # Source: Malware Domain List project
    0.0.0.0 malware-domain.com
    0.0.0.0 suspicious-site.net
  
  tracking.txt: |
    # Privacy-focused tracking blocklist
    # Source: Disconnect.me tracking protection
    0.0.0.0 google-analytics.com
    0.0.0.0 quantserve.com
    0.0.0.0 scorecardresearch.com