# Weave GitOps - Official Flux dashboard for GitOps visibility

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
  labels:
    app.kubernetes.io/name: weave-gitops
    app.kubernetes.io/component: gitops-dashboard
    app.kubernetes.io/part-of: nerv-platform
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    # Minimal resource allocation for learning environment
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # Service configuration for Traefik integration
    service:
      type: ClusterIP
      port: 9001

    # RBAC permissions for GitOps visibility
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
      additionalRules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["list", "get"]
        - apiGroups: ["source.toolkit.fluxcd.io"]
          resources: ["*"]
          verbs: ["list", "get"]
        - apiGroups: ["kustomize.toolkit.fluxcd.io"]
          resources: ["*"] 
          verbs: ["list", "get"]
        - apiGroups: ["helm.toolkit.fluxcd.io"]
          resources: ["*"]
          verbs: ["list", "get"]

    # Admin user configuration (development setup)
    adminUser:
      create: true
      username: admin
      # Password hash for 'admin123' (change in production!)
      passwordHash: "$2a$10$P/tHQ1DNFXdvX0zRGA8LQeO9DKHLlm5ByoNvEnWEj04sI9w2qE8C."
      
    # Ingress disabled - using Traefik IngressRoute instead
    ingress:
      enabled: false

    # Metrics and monitoring
    metrics:
      enabled: true