apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - alternative-storage.yaml  # OpenEBS LocalPV alternative
  - longhorn-app.yaml
  - storage-classes.yaml

namespace: default