apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.7.2"
    helm:
      skipCrds: false
      values: |
        # Single-node development configuration
        # Scales automatically to multi-node production
        
        # Disable pre-upgrade hook for initial deployment
        preUpgradeChecker:
          jobEnabled: false
        
        # Disable priority class for single-node deployment
        priorityClass: ""
        longhornManager:
          priorityClass: ""
        longhornDriver:
          priorityClass: ""
        longhornUI:
          priorityClass: ""
          nodeSelector: {}
          tolerations: []
        
        defaultSettings:
          # Storage configuration for mixed hardware support
          defaultReplicaCount: 1
          storageOverProvisioningPercentage: 200
          storageMinimalAvailablePercentage: 25
          
          # Single-node specific settings
          replicaSoftAntiAffinity: false
          allowRecurringJobWhileVolumeDetached: true
          createDefaultDiskLabeledNodes: true
          defaultDataLocality: "disabled"
          nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
          
          # Node scheduling - allow master for single-node
          taintToleration: "CriticalAddonsOnly=true:NoSchedule"
          systemManagedComponentsNodeSelector: ""
          
          # Backup and DR preparation
          backupTarget: ""
          backupTargetCredentialSecret: ""
          
        # Service configuration
        service:
          ui:
            type: LoadBalancer
            loadBalancerIP: "192.168.1.111"
            port: 80
            
        # Resource configuration for energy efficiency
        longhornManager:
          priorityClass: ""
          nodeSelector: {}
          tolerations: []
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
              
        longhornDriver:
          priorityClass: ""
          nodeSelector: {}
          tolerations: []
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        # CSI driver configuration
        csi:
          kubeletRootDir: "/var/lib/kubelet"
          attacherReplicaCount: 1
          provisionerReplicaCount: 1
          resizerReplicaCount: 1
          snapshotterReplicaCount: 1
              
        # Storage classes for different tiers
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 1
          reclaimPolicy: Retain
          
        # Monitoring integration ready
        serviceMonitor:
          enabled: false  # Enable when Prometheus deployed
          
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m