# Traefik ingress controller configuration

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingress-controller
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: traefik
      version: "37.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
    crds: CreateReplace
  rollback:
    cleanupOnFail: true
  values:
    deployment:
      enabled: true
      kind: Deployment
      replicas: 1

    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: "192.168.1.112"
      annotations:
        metallb.universe.tf/loadBalancerIPs: "192.168.1.112"
      spec:
        externalTrafficPolicy: Local

    additionalArguments:
      - "--api.dashboard=true"
      - "--ping=true"
      - "--metrics.prometheus=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=shoumeiki@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      # Performance optimizations for Traefik v3
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
      - "--accesslog=false"

    ports:
      web:
        port: 80
        expose:
          default: true
        protocol: TCP
      websecure:
        port: 443
        expose:
          default: true
        protocol: TCP
        tls:
          enabled: true
      traefik:
        port: 9000
        expose:
          default: true
        protocol: TCP

    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
        matchRule: Host(`traefik.nerv.local`)
        entryPoints:
          - websecure
        tls:
          secretName: traefik-dashboard-tls

    persistence:
      enabled: true
      name: traefik-data
      size: 1Gi
      path: /data

    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 150Mi

    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532