# MetalLB load balancer configuration

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: load-balancer
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: metallb
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    controller:
      image:
        repository: quay.io/metallb/controller
        tag: v0.14.8
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.14.8
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      # Performance optimizations for speaker
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      env:
        - name: METALLB_ML_BIND_ADDR
          value: "0.0.0.0:7472"
        - name: METALLB_ML_LABELS
          value: "app=metallb,component=speaker"

---
# Consolidated IP pool configuration - deployed atomically with MetalLB
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: nerv-pool
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: nerv-ip-pool
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: nerv-platform
spec:
  addresses:
    - 192.168.1.111-192.168.1.150

---
# Consolidated L2 advertisement - deployed atomically with MetalLB
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: nerv-l2-advertisement
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: nerv-l2-advertisement
    app.kubernetes.io/component: network
    app.kubernetes.io/part-of: nerv-platform
spec:
  ipAddressPools:
    - nerv-pool