# Longhorn distributed storage configuration

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storage
spec:
  interval: 5m
  timeout: 20m
  # Removed hard dependency - ingress will be created when Traefik is ready
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    defaultSettings:
      defaultReplicaCount: 1
      
      # Single-node optimizations
      allowVolumeCreationWithDegradedAvailability: true
      disableSchedulingOnCordonedNode: false
      replicaSoftAntiAffinity: false
      storageReservedPercentageForDefaultDisk: 10
      
      defaultDataPath: "/var/lib/longhorn"
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      backupTarget: ""  # Configure S3/NFS backup target if needed
      backupTargetCredentialSecret: ""
      autoCleanupSystemGeneratedSnapshot: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
      replicaReplenishmentWaitInterval: 600
      offlineReplicaRebuilding: true

    ingress:
      enabled: true
      host: longhorn.nerv.local

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1