# Longhorn distributed storage configuration

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.7.2"  # Latest stable version
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultSettings:
      defaultReplicaCount: 1

      defaultDataPath: "/var/lib/longhorn"
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 25
      backupTarget: ""  # Configure S3/NFS backup target if needed
      backupTargetCredentialSecret: ""
      allowVolumeCreationWithDegradedAvailability: false
      autoCleanupSystemGeneratedSnapshot: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true

    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

    longhornUI:
      replicas: 1
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"

    service:
      ui:
        type: LoadBalancer
        loadBalancerIP: "192.168.1.113"  # Reserved IP for Longhorn UI
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.1.113"

    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.nerv.local
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
        traefik.ingress.kubernetes.io/router.tls: "true"

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      defaultFsType: ext4
      reclaimPolicy: Retain

    csi:
      kubeletRootDir: "/var/lib/kubelet"
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1

    longhornInstanceManager:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule