apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kubernetes/apps
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: metallb
      namespace: metallb-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-config
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kubernetes/apps/config
  prune: true