# Longhorn distributed storage configuration

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/component: storage
spec:
  interval: 5m
  timeout: 20m
  # Removed hard dependency - ingress will be created when Traefik is ready
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    defaultSettings:
      # Essential single-node configuration
      defaultReplicaCount: 1
      allowVolumeCreationWithDegradedAvailability: true
      replicaSoftAntiAffinity: false
      
    ingress:
      enabled: true
      host: longhorn.nerv.local

    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1

    longhornManager:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi

    longhornDriver:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi