# SOPS configuration for NERV secrets
# This file defines which keys can decrypt the secrets

creation_rules:
  - path_regex: \.yaml$
    age: age14fyqqh7v5hazfmdurh8s3j58lqfuwvzy9yh2nljhlmzuyunvj3qqh74l5z