# Standard HelmRelease template for NERV platform services
# Copy this template for new services and customize the placeholders

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: SERVICE_NAME
  namespace: SERVICE_NAMESPACE
  labels:
    app.kubernetes.io/name: SERVICE_NAME
    app.kubernetes.io/component: SERVICE_COMPONENT
    app.kubernetes.io/part-of: nerv-platform
spec:
  interval: 5m
  timeout: 10m
  
  chart:
    spec:
      chart: CHART_NAME
      version: "CHART_VERSION"
      sourceRef:
        kind: HelmRepository
        name: HELM_REPO_NAME
        namespace: flux-system
      reconcileStrategy: ChartVersion
      
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
      
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
      
  rollback:
    cleanupOnFail: true
    
  values:
    # Standard resource constraints
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Standard node scheduling
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    
    # Standard security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    
    # Standard monitoring
    serviceMonitor:
      enabled: true
      namespace: SERVICE_NAMESPACE