# Minimal AdGuard Home for DNS ad-blocking
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: dns-system
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: "5.6.2"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    createNamespace: true
  values:
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            port: 3000
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    ingress:
      main:
        enabled: true
        hosts:
          - host: adguard.nerv.local
            paths:
              - path: /

    persistence:
      config:
        enabled: true
        size: 1Gi
      data:
        enabled: true
        size: 2Gi

