apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - sources/helm-repositories.yaml
  - releases/metallb/helmrelease.yaml
  - releases/cert-manager/helmrelease.yaml
  - releases/traefik/helmrelease.yaml
  - releases/longhorn/helmrelease.yaml