apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        args:
        - argocd-server
        - --insecure