apiVersion: v1
kind: Service
metadata:
  name: argocd-server-lb
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.110
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server