# GitOps health monitoring configuration

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-health-checks
  namespace: flux-system
  labels:
    app.kubernetes.io/name: flux-health-checks
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: nerv-platform
data:
  health-checks.yaml: |
    # Health check definitions for NERV platform services
    checks:
      - name: metallb-system
        namespace: metallb-system
        kind: DaemonSet
        name: metallb-speaker
        timeout: 2m
      
      - name: cert-manager
        namespace: cert-manager
        kind: Deployment
        name: cert-manager
        timeout: 2m
      
      - name: traefik-system
        namespace: traefik-system
        kind: Deployment
        name: traefik
        timeout: 2m
      
      - name: longhorn-system
        namespace: longhorn-system
        kind: DaemonSet
        name: longhorn-manager
        timeout: 5m

# ServiceMonitor removed - requires Prometheus Operator
# To enable monitoring, install Prometheus Operator first, then uncomment:
#---
#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: flux-controllers
#  namespace: flux-system
#  labels:
#    app.kubernetes.io/name: flux-controllers
#    app.kubernetes.io/component: monitoring
#spec:
#  selector:
#    matchLabels:
#      app: source-controller
#  endpoints:
#  - port: http-prom
#    interval: 30s
#    path: /metrics