# Root kustomization for NERV platform

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  - sources/helm-repositories.yaml

  - releases/metallb/helmrelease.yaml

  - metallb-config.yaml

  - releases/cert-manager/helmrelease.yaml

  - releases/traefik/helmrelease.yaml

  - releases/longhorn/helmrelease.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: nerv-platform

commonAnnotations:
  config.kubernetes.io/local-config: "false"
  fluxcd.io/managed: "true"