# Root kustomization for NERV platform

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - sources/helm-repositories.yaml
  
  # Infrastructure services (simplified linear deployment with dependsOn)
  - releases/metallb/helmrelease.yaml
  - releases/cert-manager/helmrelease.yaml
  - releases/traefik/helmrelease.yaml
  - releases/longhorn/helmrelease.yaml
  
  # Monitoring and health checks
  - flux-health-checks.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: nerv-platform

commonAnnotations:
  config.kubernetes.io/local-config: "false"
  fluxcd.io/managed: "true"
  # GitOps metadata for tracking and management
  nerv.platform/deployment-order: "infrastructure"
  nerv.platform/criticality: "high"