# External-DNS for automated DNS record management
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns-system
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: dns-automation
    app.kubernetes.io/part-of: nerv-platform
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.16.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      reconcileStrategy: ChartVersion
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  rollback:
    cleanupOnFail: true
  values:
    # Start with local DNS provider (CoreDNS) - easily switchable to cloud providers
    provider: coredns
    
    coredns:
      etcdEndpoints: "http://coredns-etcd:2379"
    
    sources:
      - ingress
      - service
      - crd
    
    domainFilters:
      - nerv.local
    
    policy: sync
    registry: txt
    txtOwnerId: "nerv-platform"
    
    interval: 1m
    logLevel: info
    
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
    
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    
    serviceMonitor:
      enabled: true
      namespace: external-dns-system